### ISSUE TITLE
Support for i18n defaultLocale

### ISSUE THREAD

**Issue by myndelx** [scottrippey/next-router-mock#22]
Hello :wave:

Is it possible to have the `defaultLocale` property support?

For example:

```ts
const {defaultLocale} = useRouter();
```

Then in our tests, we can set the default locale like this:

```ts
import routerMock from 'next-router-mock';

routerMock.defaultLocale = 'en';
```

It would be really appreciated!

**Comment by myndelx** [comment]
Hey @scottrippey! Thanks for your response!

Indeed, your solution works perfectly, both for property value and the type-safety! :-).

From what I know, I don't think it would change anything.

**Comment by scottrippey** [comment]
Created #23 for improved type defs
