### ISSUE TITLE
Can't mock in other modules with Next 12

### ISSUE THREAD

**Issue by spence-novata** [scottrippey/next-router-mock#33]
It seems like this is an issue with Next 12 as it affects other scripts in `dist/client` but apart from anything I feel like an issue in `next-router-mock` would be helpful for anyone running into the same problem.

https://github.com/vercel/next.js/issues/32964

**Comment by scottrippey** [comment]
This seems like an issue with Jest or maybe Next 12, but since it definitely can't be fixed here, I'm going to close this issue.  

Hopefully, if others have this issue, the link above will help them find a solution.
