### ISSUE TITLE
Support Dynamic Routes with Next v12 (Cannot find module 'next/dist/server/normalize-page-path')

### ISSUE THREAD

**Issue by ipatate** [scottrippey/next-router-mock#44]
hello, i have this error : 

```
Test suite failed to run

    Cannot find module 'next/dist/server/normalize-page-path' from 'node_modules/next-router-mock/dist/dynamic-routes/extensions-11.1.js'

    Require stack:
      node_modules/next-router-mock/dist/dynamic-routes/extensions-11.1.js
      components/Breadcrumb/__tests__/BreadcrumbActu.test.js

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (node_modules/next-router-mock/src/dynamic-routes/extensions-11.1.ts:9:1)
```
My version of next.js : "12.1.6"

**Comment by scottrippey** [comment]
I see.  The "dynamic-routes" feature depends on some Next internals, and the path changed between v10 and v11, and now I assume again with v12.

Some quick research shows me they might have moved the file to [`next/dist/shared/lib/page-path/normalize-page-path`](https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/page-path/normalize-page-path.ts) ...

Until a proper fix is in place, you _might_ be able to workaround the issue by adding this to your test:
```
jest.mock('next/dist/server/normalize-page-path', () => require('next/dist/shared/lib/page-path/normalize-page-path'));
```

But if that doesn't work, it looks like the "dynamic-routes" feature will need another v12 fork.

**Comment by ipatate** [comment]
thanks scott. I've tried with 
```
jest.mock('next/dist/server/normalize-page-path', () => require('next/dist/shared/lib/page-path/normalize-page-path'));
```
But for the moment, it's not work. I search a solution tomorrow.

**Comment by kjugi** [comment]
As @scottrippey correctly spotted, this file has been moved to the other path in the v12. The provided **temporary workaround** is almost fine and we have to mark this mock as a `virtual` like below:

```js
jest.mock(
  'next/dist/server/normalize-page-path',
  () => require('next/dist/shared/lib/page-path/normalize-page-path'),
  { virtual: true } // this is crucial
);
```

The jest docs about this argument: https://jestjs.io/docs/jest-object#jestmockmodulename-factory-options

> The third argument can be used to create virtual mocks – mocks of modules that don't exist anywhere in the system

**Comment by scottrippey** [comment]
I think a PR to support this would be pretty easy, since we do the same for v10 and v11. I'll see if I can get that implemented soon.

**Comment by scottrippey** [comment]
I published this as a prerelease!  Can you test this out, and lmk if it works? 

Version `0.6.8-next12.0`

**Comment by ipatate** [comment]
yes, it's work now ! with version ```0.6.8-next12.0```
and this 
```
jest.mock(
  'next/dist/server/normalize-page-path',
  () => require('next/dist/shared/lib/page-path/normalize-page-path'),
  { virtual: true } // this is crucial
);
```
thanks for your work 👍

**Comment by scottrippey** [comment]
@ipatate Can you also try without that mock? You'll need to change your import to:
```
import "next-router-mock/dynamic-routes/next-12"
```

**Comment by ipatate** [comment]
@scottrippey yes, good with this import 👏🏻 nice !

**Comment by scottrippey** [comment]
Great, published as version `0.6.8`

**Comment by kjugi** [comment]
I want to share this just for the record.

The package version `0.6.8` and `0.6.9` will work only from `12.1.6` next version. Before this, the structure was different. 

Links to the source:
- until 12.1.5: https://github.com/vercel/next.js/tree/v12.1.5/packages/next/shared/lib
- current state (from 12.1.6): https://github.com/vercel/next.js/tree/v12.1.6/packages/next/shared/lib/page-path

**Comment by scottrippey** [comment]
Thanks for mentioning it. It's getting tricky to manage all these external dependencies on Next, especially when they change without a major release. 
Just thinking out loud, at some point, maybe we could auto detect the correct version. Or maybe we could just copy the dependencies into this project. Either way, it would greatly simplify using these features.
