### ISSUE TITLE
Usage with `next/link`

### ISSUE THREAD

**Issue by pgmanutd** [scottrippey/next-router-mock#5]
First of all thank you so much for this library. Do you know how we can use it along with `next/link`? For example, clicking on a link and then checking the `pathname`? I somehow managed to make it work. Bit hacky for now:

```js
// jest.setup.js

jest.mock('next/router', () => {
  const router = require('next-router-mock');
  const i18nConfig = require('./next-i18next.config');

  router.default.locales = i18nConfig.i18n.locales;
  router.default.locale = i18nConfig.i18n.defaultLocale;

  return router;
});

jest.mock('next/link', () => {
  const { cloneElement } = require('react');
  const router = require('next-router-mock');

  return ({ children, href, replace, as, shallow, locale, scroll }) => {
    const onClick = () =>
      router.default[replace ? 'replace' : 'push'](href, as, {
        shallow,
        locale,
        scroll,
      });

    return cloneElement(children, {
      href,
      onClick,
    });
  };
});
```

and then doing `expect(router.pathname).toBe('/path/name');` in my tests.

Only problem I can see here is around resetting the `pathname`, `query`, `asPath` etc for `router` object for every test in that particular test file.

**Comment by scottrippey** [comment]
I've been looking into it, and might have found a solution...
The problem I found is that `next/link` doesn't import `next/router`, instead it imports from `next/dist/client/router`.  So I changed `jest.mock('next/router', ...)` to this:
```
jest.mock('next/dist/client/router', () => require('./router'));
```
and it seems to be working.

Can you try this solution too, and see if it works?  If so, I can probably document it and put it in the README.

Here's my complete test, which (obviously) is not comprehensive, but maybe it's a good start?
```jsx
import React from 'react';
import NextLink from 'next/link';
import { fireEvent, render, screen } from '@testing-library/react';

import MockRouter from './router';

jest.mock('next/dist/client/router', () => require('./router'));

describe('next/link', () => {
  it('should render a link', () => {
    render(<NextLink href={'/example'}>Example Link</NextLink>);
    fireEvent.click(screen.getByText('Example Link'));
    expect(MockRouter.asPath).toEqual('/example');
  });
});
```

**Comment by scottrippey** [comment]
I added these unit tests to #8  ... I still need to update the README.
I'm also curious what other `next/*` modules depend on Router, and perhaps if this fix will help those scenarios.

**Comment by pgmanutd** [comment]
> I added these unit tests to #8 ... I still need to update the README.
> I'm also curious what other `next/*` modules depend on Router, and perhaps if this fix will help those scenarios.

Seems like working for me too. Only error I can see is around [prefetch method](https://github.com/scottrippey/next-router-mock/blob/main/src/MemoryRouter.tsx#L74), where it is throwing **NotImplemented** error when I am running `jest-axe` tests.

**Comment by markplindsay** [comment]
Hi @scottrippey, thanks for writing `next-router-mock`. I'm trying to get clicks on `next/link` working in my app as well.

@pgmanutd's `next/link` mock in `jest.setup.js` works. Nice!

Calling
```
jest.mock('next/dist/client/router', () => require('next-router-mock'))
```
instead of
```
jest.mock('next/router', () => require('next-router-mock'))
```
does not work, unfortunately. It breaks my tests with the `NotImplemented` error.

**Comment by scottrippey** [comment]
@markplindsay Will you check if you're on the latest version, `0.2.3` ?  
I think that `Not Implemented` error might have been coming from `prefetch`, which I patched in `0.2.3` to not throw anymore.

**Comment by pgmanutd** [comment]
+1 to @scottrippey. Here is the [PR](https://github.com/scottrippey/next-router-mock/pull/8) with changes.

**Comment by pgmanutd** [comment]
@scottrippey: Thanks for the latest version. It works seamlessly. All the tests are passing and I also removed `next/link` mocking. [Here is the change](https://github.com/Open-Speech-EkStep/crowdsource-dataplatform/commit/1fdefe9abec504f171177ccb2520262c177baf87) if it helps anyone.

**Comment by pgmanutd** [comment]
Fixed with https://github.com/scottrippey/next-router-mock/pull/8

**Comment by markplindsay** [comment]
@scottrippey, yep! I was on `0.2.2`. Using `0.2.3` and mocking `next/dist/client/router` instead of `next/router` works perfectly.

Thanks again to you and @pgmanutd.
