### ISSUE TITLE
Getting `MaxListenersExceededWarning` for `routeChangeComplete` when multiple `next/link` components are used

### ISSUE THREAD

**Issue by pgmanutd** [scottrippey/next-router-mock#6]
Getting `MaxListenersExceededWarning` for `routeChangeComplete` when multiple `next/link` components are used, for example in `Header` component (if component is using `useRouer` from `next/router`):
![image](https://user-images.githubusercontent.com/7638708/130412001-a29fba24-57e0-43a3-8ca0-774ccbfe0c4a.png)

There is a workaround though. We can add this line in the jest setup file:

`require('events').prototype.setMaxListeners(200);`

**Comment by pgmanutd** [comment]
Looks like `next/router` uses a [modified version](https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/mitt.ts) of [mitt](https://www.npmjs.com/package/mitt) library for dispatching events. Can we use `mitt` instead of `events` module?

**Comment by scottrippey** [comment]
I'd be happy to use `mitt` if that brings us inline with the Next  implementation!  I'll see if I can get to it, but if you want to create a PR please lmk.

**Comment by scottrippey** [comment]
Any idea why so many event listeners are being added?  Maybe there's an actual memory leak in this implementation?  Seems like `mitt` just doesn't have memory-leak detection.

**Comment by pgmanutd** [comment]
> Any idea why so many event listeners are being added? Maybe there's an actual memory leak in this implementation? Seems like `mitt` just doesn't have memory-leak detection.

`next/link` [internally](https://github.com/vercel/next.js/blob/canary/packages/next/client/link.tsx#L214) uses `useRouter`, and with `next-router-mock`'s [current implementation](https://github.com/scottrippey/next-router-mock/blob/main/src/router.tsx#L10), `memoryRouter.events.on("routeChangeComplete", handleRouteChange)` will be called everytime a new `next/link` is rendered. If `next/link` count goes beyond `11`, `MaxListenersExceededWarning` will be thrown.

And you are right about memory leak detection, next team uses a [modified version](https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/mitt.ts) of `mitt`, wherein they just push into an array of listeners without any max limit count (which we have in case of `events` package).


> I'd be happy to use `mitt` if that brings us inline with the Next implementation! I'll see if I can get to it, but if you want to create a PR please lmk.

Sure I can create a PR if we think `mitt` works here. It's working atleast for [my case](https://github.com/Open-Speech-EkStep/crowdsource-dataplatform/commit/b0fa659b74ddbc5f3caffef9c75ec270a211663b) 😅

**Comment by scottrippey** [comment]
Oh, I see!  With `events` we start to get warnings when you render more than 10 links.  It seems reasonable to allow more than 10 links!
I looked at `mitt` and it seems perfect, small and lightweight, and especially useful since it's what Next used.  Let's switch!

**Comment by pgmanutd** [comment]
> Oh, I see! With `events` we start to get warnings when you render more than 10 links. It seems reasonable to allow more than 10 links!
> I looked at `mitt` and it seems perfect, small and lightweight, and especially useful since it's what Next used. Let's switch!

Cool! Should we just install `mitt` or use this [simple modified version](https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/mitt.ts) next is using?

**Comment by scottrippey** [comment]
Ready for review in #7 !

**Comment by pgmanutd** [comment]
Fixed with https://github.com/scottrippey/next-router-mock/pull/7
