### ISSUE TITLE
Router.push "as" parameter not working

### ISSUE THREAD

**Issue by mauriceackel** [scottrippey/next-router-mock#63]
Hi @scottrippey,

thanks for providing this library! We are currently facing the issue that we want to test the following code using the library:
```js
const pathWithParams = '/our/path?with=params';
const pathWithoutParams = '/our/path'

router.push(pathWithParams, pathWithoutParams);
```

We write our assertion as follows:
```js
expect(SingletonRouter).toMatchObject({
  pathname: '/our/path',
  asPath: '/our/path',
  query: {
    with: 'params',
  },
});
```

However, this assertion will fail, as the `asPath` property will have the value: `/our/path?with=params`. In our opinion, this is wrong as the `asPath` property should have the same value that is passed as the second parameter of the `push` (or `replace`) function.

After looking at the code, we found the following function: https://github.com/scottrippey/next-router-mock/blob/fbe8950695369c1d46de6c3cc9202187ef3d0ac0/src/MemoryRouter.tsx#L153
This faction receives an `as` parameter (e.g. from the `push`) function.  However, this parameter is never used in the function. Instead to compute the `asPath` property, the following line is used: https://github.com/scottrippey/next-router-mock/blob/fbe8950695369c1d46de6c3cc9202187ef3d0ac0/src/MemoryRouter.tsx#L168

~In our opinion, this should be changed to~
```js
const asPath = as ?? getRouteAsPath(newRoute.pathname, newRoute.query, newRoute.hash);
```
~(note the `as ??` part). To make sure the functionality matches the actual functionality from the Next Router. By implementing it this way, the `as` parameter will be used if it is defined and if it is not defined, it will fall back to the current functionality.~

**See the linked PR for our approach on how to solve this.**

What do you think? Is this reasoning valid? Should we open a PR or would you rather add it yourself?

Cheers 👋

**Comment by scottrippey** [comment]
I haven't personally used the `as` param, so I never implemented it. But I'm grateful for your solution! I'll look at the PR and continue the discussion there.
