### ISSUE TITLE
feat request: drop support for nextjs 10.x

### ISSUE THREAD

**Issue by jantimon** [scottrippey/next-router-mock#65]
hi :)

would it be possible to drop next 10 in a major update?

Vite is not able to compile `next-router-mock` as it can't resolve imports inside `src/MemoryRouterProvider/next-10.tsx`

**Comment by scottrippey** [comment]
Yes I'll consider it, but first I'd like to check if there's a simple workaround?

First off, are you importing from this path?
```
import { MemoryRouterProvider } from 'next-router-mock/MemoryRouterProvider';
```
A simple workaround would be to change it to:
```
import { MemoryRouterProvider } from 'next-router-mock/MemoryRouterProvider/next-12';
```

This way, there's no references to the `next-10.tsx` file.

However, if you're not importing from that path, is Vite just loading ALL code from the entire `node_modules/next-router-mock/src/*` codebase?  That would be very problematic, so I'm not sure if removing `next-10.tsx` would even fully solve the problem.  Hopefully the above workaround works.
