### ISSUE TITLE
Mock router doesn't update with `userEvent`

### ISSUE THREAD

**Issue by eXodes** [scottrippey/next-router-mock#69]
## Background

Currently, I am using this library to run testing on our app. However, I seems not being able to make it work with `userEvent`. I apologise beforehand if this is a known issue.

## Problems

Render with NextLink and try clicking the link using `userEvent` will cause the test to fail.

## Expectation

Mock router `asPath` value to be updated with the URL href value.

## Actual

Mock router `asPath` doesn't changed even though click has been triggered.

## Repro
https://codesandbox.io/p/sandbox/next-jest-rtl-qs1w9l

**Comment by markplindsay** [comment]
@eXodes make sure you're using `next-router-mock@0.9.1` [as Scott mentioned here](https://github.com/scottrippey/next-router-mock/issues/58#issuecomment-1408052341).

I was having the same problem, but then I checked `npm ls next-router-mock` and discovered I was on an older version.

**Comment by scottrippey** [comment]
One difference between `fireEvent` and `userEvent` is that all actions are async.  So, in your test, you must have `await userEvent.click(...)` (and mark the function `async` too).

It seems to fix the problem:
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/430608/220196542-2b81c29d-3cfa-4510-ac46-830ec06222ba.png">
