### ISSUE TITLE
Modify the as param condition

### ISSUE THREAD

**Issue by leedoopal** [scottrippey/next-router-mock#70]
Hi! 

I have something to suggest while using it, so I am registering an issue.
Can I change the condition of as parameter to `falsy values` other than `undefined`?
https://github.com/scottrippey/next-router-mock/blob/f212a96d1ad82f743676d044800a0185b3dcd841/src/MemoryRouter.tsx#L145-L147

I wish change
```typescript
if (!as) {
      asRoute = undefined;
      asPath = getRouteAsPath(newRoute.pathname, newRoute.query, newRoute.hash);
```

What do you think? Have a good day 🙂

**Comment by scottrippey** [comment]
The goal of this lib is to reproduce Next's behavior as closely as possible.  If Next supports falsey values, then that sounds fine.  However, I know that `""` empty string should be considered a valid URL, so I'd probably only want to consider `as === undefined || as === null` .
I'd be fine if you created a PR with this change!

**Comment by leedoopal** [comment]
@scottrippey thanks, I created
