### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by DjebbZ** [scottrippey/next-router-mock#75]
Hello,

It would be nice if you could add a changelog, either via the Github releases page or via a CHANGELOG.md file.

Here's some guidance about how to format a changelog : https://keepachangelog.com/en/1.0.0/

There must some tools that can automate (part of) the work, I haven't looked into it though to find the one that fits your workflow best.

Thank you!

**Comment by scottrippey** [comment]
Agreed, I'd like to use [changesets](https://github.com/changesets/changesets) to automate the release cycle of this repo, including changelog + releases.  Thanks for opening this issue! I'll update once this gets added.

**Comment by scottrippey** [comment]
Completed in #100 !  Thanks for the suggestion.
